# Generated by Django 5.2.9 on 2026-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
